### ISSUE TITLE
Roadmap to Version 1.0

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs-webui#46]
Some ideas of improvement to discuss.

### Pagination

The `react` tag page contains almost 100 projects.
https://bestof.js.org/tags/react

We need either pagination or infinite scrolling to make the page faster.
Also, this pagination solution would be applied to the `ALL PROJECTS` and `HALL OF FAME` pages.

### See project dependencies

When you have to pick a npm package to perform a given task, one of the main of the main arguments is the number of dependencies.

So I think it would be useful to be able to see the list of project dependencies.

### User Content loading

> When the app loads, we fetch all data about user's reviews and links, even if reviews and links are **NOT** displayed inside the project cards.

> We make 2 `GET` requests to get **all** reviews and **all** links
* https://webtask.it.auth0.com/api/run/wt-mikeair-gmail_com-0/user-content-api-v3/reviews
* https://webtask.it.auth0.com/api/run/wt-mikeair-gmail_com-0/user-content-api-v3/links

> It works fine because we have very little few links and reviews.

> It would be better to fetch only data about a given project when the user opens a project page (`/projects/:slug/` url)

This point has been addressed by this PR #48 

### Refreshing data

If you keep the browser open for more than 24 hours, data will be out-dated.
The only way to to get fresh data is to trigger a browser reload (F5).

It would be nice if data was automatically reloaded when it's needed.

### Search box and tags

It would be nice if tags could be selected right from the search box, because the tag list is really long, it takes time to scroll down.

### Heatmap about daily stars

See https://github.com/michaelrambeau/bestofjs-webui/issues/33

## More advanced

The application was made from scratch, without using any framework.
The landscape has changed a lot since 2015.

Could we take advantage of solutions like `create-react-app`, `next.js` or `Gatsby` to implement the following features?

* A better server-side rendering
* Offline support
* Code splitting 
* CSS-in-JS

**Comment by michaelrambeau** [comment]
## One year later

One year later, the version 1 has not been released yet!

### What has been done

The biggest change happened with release 0.12, we use now `create-react-app` instead of the custom webpack set up.

* [x] CSS-in-JS: done! (`styled-components`)
* [x] Code splitting: done!
* [X] Heatmap: done! (#33)
* [X] Reload data when it's needed: done!
* [X] Pagination: done!
* [X] Project dependencies: done! (#48 )
* [X] User content loading: done!

TODO:

* [ ] SSR
* [ ] New search feature

### Improve performance and make things more scalable

The biggest issue is about the performance, I feel like the application is slow because we handle too much data in the Redux store (more than 1300 projects!)

I rewrote UI tests, using a new approach, and numbers show that it takes too much time to render the application and to navigate from one page to an other.

![image](https://user-images.githubusercontent.com/5546996/42751793-e0eb44b4-8926-11e8-92f6-fe079bc167f1.png)

For example, it tooks almost 10 seconds to run the test about "All Projects" page.
The test loads renders the page and goes to all "Trending" tabs ("Today", "This week", ...)

```js
const routes = [
  '/projects/trending/today',
  '/projects/trending/this-week',
  '/projects/trending/this-month',
  '/projects/trending/last-3-months',
  '/projects/trending/last-12-months'
]

it('Should render the `All projects` page', async () => {
  const { mainNode, history } = renderApp({ route: '/projects' })
  await wait(() => getByText(mainNode, 'All projects'))
  const testPage = route => {
    history.push(route)
    getByText(mainNode, /Popular/i)
    getByText(mainNode, /Trending/i)
    getByText(mainNode, /Vue/i)
  }
  routes.forEach(testPage)
})
```

Rather than loading everything (the whole list of projects) when the application starts, it's maybe time to think about a new strategy:

* Define the "shell" of the application, that is to say the information needed to show the home page: the available tags, the top 10 projects maybe
* Load everything else on-demand

**Comment by michaelrambeau** [comment]
## The point in 2019, 2 years later

The user generated content (links and reviews) feature will be dropped in the version 0.19

The reason: nobody really uses this feature

- 170 links were created (98 from me)
- 102 reviews were created (10 from me)

We might restore the feature later.

Among the main points to improve to get the point the application can be labelled "V1.0":

### A better tagging system

- We should be able to filter using several "tags". Especially when we search for React or Vue.js components.
- There should alias for some tags (E.g. `carousel` and `slider` are the same things, we should be able to find projects used either one term on an other)
- Some tags may include (or be related) to some other tags. For example `Testing framework` is a subset of `Testing tools`

### A more attractive homepage

The homepage should show the diversity of the projects tracked by the application.
The sidebar could be hidden by default, even on desktop?

## Improve performance

See above.

**Comment by michaelrambeau** [comment]
Closing as several issues were addressed (including the attempt to make the home page more attractive). We need a new road map in 2021.
